Add deprecated license field for backward compatibility with older setuptools versions
The license field was deprecated and replaced by the license-expression
field. However, older setuptools versions still require the license
field:

distutils.errors.DistutilsOptionError: No configuration found for dynamic 'license'.
Some dynamic fields need to be specified via `tool.setuptools.dynamic`
others must be specified via the equivalent attribute in `setup.py`.