Workaround backward compatibility issues with older setuptools versions due to license-files
The license-files field in the pyproject.toml was not allowed in
older setuptools versions:

ValueError: invalid pyproject.toml config: `project`.
configuration error: `project` must not contain {'license-files'} properties

This commit worksaround the issue by moving the license-files back
to setup.py.