Fix private_torrent_test
Fixes the following traceback:

Traceback (most recent call last):
  File "test/test.py", line 1888, in <module>
    failed += all_tests()
  File "test/test.py", line 1764, in all_tests
    private_torrent_test()
  File "test/test.py", line 1539, in private_torrent_test
    test_log_results('should not contain private flag', 0, repr(data), needle in data, None)
TypeError: a bytes-like object is required, not 'str'