Fix create_funkynames test
This fixes the following traceback:

Traceback (most recent call last):
  File "test/test.py", line 1888, in <module>
    failed += all_tests()
  File "test/test.py", line 1796, in all_tests
    C_funkynames_test(t)
  File "test/test.py", line 776, in C_funkynames_test
    num = create_funkynames(t, d, chr, deep=deep)
  File "test/test.py", line 749, in create_funkynames
    f.write('%02x' % i)
TypeError: a bytes-like object is required, not 'str'