Fix buffer overflow when retrieving terminal size
Since Python 3.14 buffer sizes are checked on ioctls (see
https://github.com/python/cpython/issues/132915).

This uncovered a buffer overflow in getscrwidth() when retrieving the
terminal size:

ERROR: test_getscrwidth (test_term.TermTestCase.test_getscrwidth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cfv/cfv/test/test_term.py", line 38, in test_getscrwidth
    self.assertEqual(term.getscrwidth(), 80)
                     ~~~~~~~~~~~~~~~~^^
  File "/home/runner/work/cfv/cfv/lib/cfv/term.py", line 16, in getscrwidth
    h, w = struct.unpack('h h', ioctl(tty.fileno(), TIOCGWINSZ, '\0' * struct.calcsize('h h')))
                                ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SystemError: buffer overflow

Fixes #76