CI: Allow failures for optional dependencies on Python 3.15
The blake8 dependency uses PyO3 which currently does not support Python 3.15 yet:

  error: the configured Python interpreter version (3.15) is newer than PyO3's maximum supported version (3.14)
  = help: please check if an updated version of PyO3 is available. Current version: 0.26.0
  = help: set PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1 to suppress this check and build anyway using the stable ABI

As Python 3.15 is still pre-release, we just allow failures for now.